### ISSUE TITLE
请教app和web端jwt各自独立的问题

### ISSUE THREAD

**Issue by ygcool** [phper666/jwt-auth#19]
请教单点登录如何实现，app、web端的token各自只能有一个有效

**Comment by phper666** [comment]
@ygcool 我的想法是加多一个场景值的配置，每个场景值对应一份jwt的配置，然后黑名单根据场景值的key+sso的uid来存储数据，这样在校验黑名单的时候就能区分不同场景的数据了。我们这边都是用多点登录，然后在jwt里面绑定场景值来区分应用的，你这个需求我想想看看，应该可以实现

**Comment by ygcool** [comment]
感谢！

**Comment by phper666** [comment]
@ygcool 可以是用3.0.x版本，支持了多应用

**Comment by ygcool** [comment]
> @ygcool 可以是用3.0.x版本，支持了多应用

厉害厉害！！ 支持
