### ISSUE TITLE
是否考虑添加webSocket也添加header Sec-WebSocket-Protocol

### ISSUE THREAD

**Issue by gg22mm** [phper666/jwt-auth#21]
是否考虑添加webSocket也添加header Sec-WebSocket-Protocol?   我看到现在用的是： ['middleware' => [Phper666\JwtAuth\Middleware\JwtAuthMiddleware::class]]

是不是我自己新建一个中间件即可

**Comment by phper666** [comment]
@gg22mm 你websocket也是用jwt生成的token吗？感觉不需要中间件，可以在握手的时候就验证了，你用中间件也可以，直接在你的中间件获取到Sec-WebSocket-Protocol然后再验证就可以了。建议使用3.0.x版本，支持多应用的场景

**Comment by gg22mm** [comment]
多谢，到时我试试
