### ISSUE TITLE
请求 Hyperf 2.0 支持

### ISSUE THREAD

**Issue by StringKe** [phper666/jwt-auth#22]

**Comment by phper666** [comment]
hyperf2.0发布后，会直接适配

**Comment by lipengbo89** [comment]
hyperf2.0已经发布

**Comment by guanhui07** [comment]
适配下hyperf2.0 这边升级 就差jwt-auth包 依赖的是v1.1

**Comment by ygcool** [comment]
铁子，hyperf 2.0升级，"phper666/jwt-auth": "~3.0.0"  貌似不支持

**Comment by phper666** [comment]
@guanhui07 老哥们不要急，我中午休息的时候再测试，测试好了再发布

**Comment by phper666** [comment]
@guanhui07 @ygcool @StringKe @lipengbo89 以兼容
