### ISSUE TITLE
麻烦尽快调整 hyperf 依赖到 2.0 阶段

### ISSUE THREAD

**Issue by Han-MeiM** [phper666/jwt-auth#24]
## Hyperf 已经发布最新的 2.0 版本
由于该包对 hyperf 依赖还在 1.1 阶段的问题，导致无法整体升级框架
麻烦尽快更新依赖好吗？

**Comment by phper666** [comment]
@Han-MeiM 中午的休息的时候我会测试然后再发布

**Comment by maxincai** [comment]
> @Han-MeiM 中午的休息的时候我会测试然后再发布

加油，等着升级。

**Comment by phper666** [comment]
@Han-MeiM @hedeqiang 以兼容

**Comment by hedeqiang** [comment]
强，我还没升级，升级的时候看下@phper666

**Comment by zhengyingming** [comment]
为啥我hyperf2.0安装jwt3.0.x，我用你的demo，登录能成功获取到token， 获取数据时 在路由中使用jwt中间键  /v1/data，报错误： 报错：No entry or class found for 'Phper666\JwtAuth\Middleware\JwtAuthMiddleware'。

**Comment by zhengyingming** [comment]
> 为啥我hyperf2.0安装jwt3.0.x，我用你的demo，登录能成功获取到token， 获取数据时 在路由中使用jwt中间键 /v1/data，报错误： 报错：No entry or class found for 'Phper666\JwtAuth\Middleware\JwtAuthMiddleware'。

可以了，我把包删除了，重新再把包安装后就可以了。非常感谢作者提供这么好用的工具。
