### ISSUE TITLE
请问3.0.3的版本与3.0.2的实现代码怎么不一样呢？

### ISSUE THREAD

**Issue by xskjs888** [phper666/jwt-auth#25]
之前用的3.0.1。jwt类名改成了大写
更新了3.0.3，jwt类 又变回了 2.0的样子。
是什么原因呢？

**Comment by phper666** [comment]
@xskjs888 不会呀，3.0.3变回了2.0？

**Comment by phper666** [comment]
@xskjs888 很抱歉，我发布的3.0.3没有注意，直接使用了master，我刚刚发布了一个最新的版本，3.0.4，是使用了3.0.x最新的代码，很抱歉~

**Comment by xskjs888** [comment]
> @xskjs888 很抱歉，我发布的3.0.3没有注意，直接使用了master，我刚刚发布了一个最新的版本，3.0.4，是使用了3.0.x最新的代码，很抱歉~

没事，非常感谢您的组件。
