### ISSUE TITLE
报错: No entry or class found for 'Phper666\JwtAuth\Middleware\JwtAuthMiddleware'

### ISSUE THREAD

**Issue by nilsir** [phper666/jwt-auth#27]
"phper666/jwt-auth": "~3.0.0"  v3.0.4
"hyperf/framework": "~2.0.0", v2.0.3

**Comment by phper666** [comment]
@nilsir 是JWTAuthMiddleware不是JwtAuthMiddleware

**Comment by nilsir** [comment]
> @nilsir 是JWTAuthMiddleware不是JwtAuthMiddleware

根据master下的readme复制的, master的readme要改下;已经修改为正确的名称, 但是还是报相同的错误

**Comment by nilsir** [comment]
> @nilsir 是JWTAuthMiddleware不是JwtAuthMiddleware

提了pr了, 麻烦合并下, 报错是因为命名空间不对

**Comment by phper666** [comment]
2.+的是JwtAuthMiddleware
