### ISSUE TITLE
若黑名单缓存不存在时 会产生一个NOTICE

### ISSUE THREAD

**Issue by Dmcz** [phper666/jwt-auth#29]
如图， 若缓存不存在，从cache中会返回null，取值['valid_until']时会产生NOTICE
![image](https://user-images.githubusercontent.com/14307285/90161868-60789600-ddc6-11ea-8d6e-3e693a38d481.png)

**Comment by phper666** [comment]
晚点我优化下~thx~

**Comment by phper666** [comment]
可以更新到4.0.2试试，4.x只支持php7.4以上

**Comment by Dmcz** [comment]
ok, thx.
