### ISSUE TITLE
请问生成的token保存在哪里？redis里没找到

### ISSUE THREAD

**Issue by dongysh** [phper666/jwt-auth#31]

**Comment by phper666** [comment]
@dongysh 具体你看下你的缓存用了文件缓存还是redis缓存？

**Comment by dongysh** [comment]
使用的是redis，下面是cache.php配置

return [
    'default' => [
        'driver' => Hyperf\Cache\Driver\RedisDriver::class,
        'packer' => Hyperf\Utils\Packer\PhpSerializerPacker::class,
        'prefix' => 'c:',
    ],
];

**Comment by phper666** [comment]
@dongysh 你有打开黑名单吗？打开黑名单并且刷新过token才会有

**Comment by dongysh** [comment]
黑名单打开的，刷新了token，出现了redis数据，但是没看到原始token信息

我想知道下面这串token存在哪？目前我用的是hyperf2.0和jwt-auth2.0.1

{
    "code": 0,
    "msg": "获取token成功",
    "data": {
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1ZjQ1ZDFmOTM4Y2I3IiwiaWF0IjoxNTk4NDExMjU3LCJuYmYiOjE1OTg0MTEyNTcsImV4cCI6MTU5ODQxODQ1NywidWlkIjoxLCJ1c2VybmFtZSI6Inh4In0.17IeJtApWjrlAV4_IiKDvbBTuAQTfURVdfH_etxzmao"
    }
}

**Comment by phper666** [comment]
你看下文档，并不会存token------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;dongysh&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年8月26日(星期三) 中午11:41
收件人:&nbsp;&quot;phper666/jwt-auth&quot;<jwt-auth@noreply.github.com&gt;;
抄送:&nbsp;&quot;phper666&quot;<562405704@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [phper666/jwt-auth] 请问生成的token保存在哪里？redis里没找到 (#31)

**Comment by dongysh** [comment]
好的，我看下，谢谢
