### ISSUE TITLE
Error while injecting dependencies

### ISSUE THREAD

**Issue by zhengwenle** [phper666/jwt-auth#37]
按照你的案例，我本地测试报这个错误，代码没任何改动。
Error while injecting dependencies into App\Controller\IndexController: No entry or class found for 'Phper666\JwtAuth\Jwt'[101] in /home/wwwroot/platform/api/vendor/hyperf/di/src/Resolver/ObjectResolver.php

**Comment by phper666** [comment]
@zhengwenle 找不到这个类，你现在用的是哪个版本的？2.0.x版本和3.0.x版本类名有改变，具体可以切换分支查看，对应的分支下会有文档说明

**Comment by zhengwenle** [comment]
我用的3.0.x

**Comment by phper666** [comment]
@hedeqiang 3.0.x没有Jwt这个类了，你切换分支看下文档

**Comment by zhengwenle** [comment]
好的，我修改过了，谢谢。

**Comment by hedeqiang** [comment]
@phper666  好久没用了，没太注意了，看了下 README ，太乱了无从下手，新手进来不知道如何做处理。建议去掉不必要的描述。改动的东西加一个 CHANGELOG 。这样看起来舒服一点

**Comment by phper666** [comment]
@hedeqiang 好的，我抽空再改下，最近在转语言，所以都好久没空弄这个了
