### ISSUE TITLE
DateTimeImmutable 错误

### ISSUE THREAD

**Issue by yu798842325** [phper666/jwt-auth#38]
Deprecated: Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. in /www/wwwroot/www.hf001.com/vendor/lcobucci/jwt/src/Builder.php on line 151
PHP Deprecated:  Using integers for registered date claims is deprecated, please use DateTimeImmutable objects instead. in /www/wwwroot/www.hf001.com/vendor/lcobucci/jwt/src/Builder.php on line 151

依赖lcobucci/jwt 更新，更换了时间的处理方法。当前组件没有传递参数没有更新造成了报错。 
https://github.com/lcobucci/jwt/issues/550

**Comment by jqcool** [comment]
这么严重的问题，没有更新吗，整个组件都用不了了

**Comment by phper666** [comment]
我已经更新了啊，你现在用的是哪个版本？

**Comment by jqcool** [comment]
好了，刚更新升级到了3.0.5，你回复后我再更新才到了3.0.6，现在可以使用了，谢谢

--------------原始邮件--------------
发件人："phper666 "<notifications@github.com&gt;;
发送时间：2020年11月30日(星期一) 中午11:40
收件人："phper666/jwt-auth" <jwt-auth@noreply.github.com&gt;;
抄送："jqcool "<admin@jqcool.net&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [phper666/jwt-auth] DateTimeImmutable 错误 (#38)
-----------------------------------

 

 
我已经更新了啊，你现在用的是哪个版本？
