### ISSUE TITLE
直接调用token 明明头部传了token 但是还一只i提示 A token is required

### ISSUE THREAD

**Issue by fengyikang88** [phper666/jwt-auth#41]
if  ($this->jwt->logout())  {
            return $this->successJson('退出登录成功');
        }
        return $this->failJson('退出登录失败');

 $token = $this->request->getHeaderLine('Authorization') ?? '';
这个方法拿不到头部的token

**Comment by phper666** [comment]
可以拿到的

**Comment by phper666** [comment]
没见有后续回复，先关闭
