### ISSUE TITLE
多点登陆时间半个小时就不行了。

### ISSUE THREAD

**Issue by mofeier** [phper666/jwt-auth#42]
多点登陆时前边登陆过的数据，差不多半个小时就不行了。是所有的登陆都不行了，不是只有前边登陆的，后边登陆的数据也失效了。

**Comment by phper666** [comment]
@mofeier 过期时间设置了多少？

**Comment by mofeier** [comment]
7200秒
场景：测试多点登陆。 浏览器：Safari、谷歌、火狐。 时间：设置7200秒，黑名单默认的86400.   scene 设置全部都是 mpop ，default 设置 application3
测试：
1、测试黑名单，同登陆入口，后面登陆，前面token存在一定的时间，大概10几分钟左右就全部掉了。 
2、测试多点登陆，自动登出时间不等，有时是20多分钟，有时30多分钟。

**Comment by phper666** [comment]
@mofeier 你们缓存是用redis吗？看下redis上的数据

**Comment by mofeier** [comment]
a:4:{s:9:"_previous";a:1:{s:3:"url";s:40:"http://127.0.0.1:9501/merchant/dashboard";}s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}s:13:"Authorization";s:290:"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkZWZhdWx0XzYwNzc4ZjYyYWU5OTc2LjAwNDcyMjA1IiwiaWF0IjoxNjE4NDQ4MjI2LCJuYmYiOjE2MTg0NDgyMjYsImV4cCI6MTYxODQ1NTQyNiwibWVyX2lkIjo0LCJ1c2VybmFtZSI6Ilx1NmQ0Ylx1OGJkNSIsImp3dF9zY2VuZSI6ImRlZmF1bHQifQ.tBaNrdXWMu1g_izVJxZti4H4tlhcnbe3pZOX92lwleg";s:8:"username";s:6:"测试";}

**Comment by mofeier** [comment]
a:4:{s:9:"_previous";a:1:{s:3:"url";s:40:"http://127.0.0.1:9501/merchant/dashboard";}s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}s:13:"Authorization";s:290:"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJkZWZhdWx0XzYwNzc4ZjYyYWU5OTc2LjAwNDcyMjA1IiwiaWF0IjoxNjE4NDQ4MjI2LCJuYmYiOjE2MTg0NDgyMjYsImV4cCI6MTYxODQ1NTQyNiwibWVyX2lkIjo0LCJ1c2VybmFtZSI6Ilx1NmQ0Ylx1OGJkNSIsImp3dF9zY2VuZSI6ImRlZmF1bHQifQ.tBaNrdXWMu1g_izVJxZti4H4tlhcnbe3pZOX92lwleg";s:8:"username";s:6:"测试";}

**Comment by mofeier** [comment]
嗯。是我错了。。修改了Redis 的 option 时间（默认是没有的），这次可以到2小时了。。另外 session也改了默认时间。
