### ISSUE TITLE
更新~3.0.x出现报错

### ISSUE THREAD

**Issue by guihouchang** [phper666/jwt-auth#43]
PHP Fatal error:  Uncaught ReflectionException: Class Phper666\JwtAuth\Jwt does not exist in /Users/guihouchang/Desktop/project/www/hyperf-mall/vendor/hyperf/di/src/Definition/DefinitionSource.php:81

好像是di无法加载这个类

**Comment by phper666** [comment]
@guihouchang 看下3.0.x分支的文档例子，类名改变了

**Comment by guihouchang** [comment]
> @guihouchang 看下3.0.x分支的文档例子，类名改变了

嗯，我看到了。 唉，要改好多！
