### ISSUE TITLE
无效的token，走到黑名单检测的时候。blacklist.php 第97行。出现undefined

### ISSUE THREAD

**Issue by yhuaao** [phper666/jwt-auth#44]
if ($config['blacklist_enabled'] && $config['login_type'] == 'sso') {
            $val = $this->cache->get($cacheKey);
            // 这里为什么要大于等于0，因为在刷新token时，缓存时间跟签发时间可能一致，详细请看刷新token方法
            $isFuture = ($claims['iat'] - $val['valid_until'] ?? 0) >= 0;   ./////////////////////////// 兼容修改  ??0
            // check whether the expiry + grace has past
            return !empty($val) && !$isFuture;
        }

**Comment by phper666** [comment]
@jiakai771628 无效的token？你的意思是随便生成的token吗？

**Comment by yhuaao** [comment]
黑名单缓存不存在时

**Comment by phper666** [comment]
更新到4.0.x试试，4.x只支持php7.4以上

**Comment by phper666** [comment]
先关闭该issues
