### ISSUE TITLE
Install of lcobucci/jwt,phper666/jwt-auth failed

### ISSUE THREAD

**Issue by xiucaiwu** [phper666/jwt-auth#45]
PHP版本7.4.20
Hyperf版本2.1.22
非docker
报错信息如下
`  - Installing lcobucci/jwt (3.3.3): Extracting archive
Executing async command (CWD): unzip -qq  '/data/wwwroot/hyperf-skeleton/vendor/composer/tmp-387a0d043e10c710a329528c6760fa20' -d '/data/wwwroot/hyperf-skeleton/vendor/composer/047e3862'
    Install of lcobucci/jwt failed
  - Installing phper666/jwt-auth (v3.0.6): Extracting archive
Executing async command (CWD): unzip -qq  '/data/wwwroot/hyperf-skeleton/vendor/composer/tmp-fc1b37f7084f0ae91f6588a23b2cec5f' -d '/data/wwwroot/hyperf-skeleton/vendor/composer/63923d7d'
    Install of phper666/jwt-auth failed
Downloading https://packagist.org/downloads/
[201] https://packagist.org/downloads/

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

                                                    
  [RuntimeException]                                                        
  Could not delete /data/wwwroot/hyperf-skeleton/vendor/composer/e7956d8f:`

**Comment by phper666** [comment]
看起来像源的问题，你换个国内源



发自我的iPhone


------------------ Original ------------------
From: xiucai.me ***@***.***&gt;
Date: Tue,Jun 29,2021 8:40 PM
To: phper666/jwt-auth ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [phper666/jwt-auth] Install of lcobucci/jwt,phper666/jwt-auth failed (#45)





 
PHP版本7.4.20
 Hyperf版本2.1.22
 非docker
 报错信息如下
 `  - Installing lcobucci/jwt (3.3.3): Extracting archive
 Executing async command (CWD): unzip -qq  '/data/wwwroot/hyperf-skeleton/vendor/composer/tmp-387a0d043e10c710a329528c6760fa20' -d '/data/wwwroot/hyperf-skeleton/vendor/composer/047e3862'
 Install of lcobucci/jwt failed
  
Installing phper666/jwt-auth (v3.0.6): Extracting archive
 Executing async command (CWD): unzip -qq  '/data/wwwroot/hyperf-skeleton/vendor/composer/tmp-fc1b37f7084f0ae91f6588a23b2cec5f' -d '/data/wwwroot/hyperf-skeleton/vendor/composer/63923d7d'
 Install of phper666/jwt-auth failed
 Downloading https://packagist.org/downloads/
 [201] https://packagist.org/downloads/ 
 
Installation failed, reverting ./composer.json and ./composer.lock to their original content.
 
[RuntimeException]
 Could not delete /data/wwwroot/hyperf-skeleton/vendor/composer/e7956d8f:`

**Comment by xiucaiwu** [comment]
默认源和国内的阿里云源都试过了,还是一样的错误

**Comment by phper666** [comment]
@xiucaiwu 
1、删除 composer.lock
2、composer clearcache 清除缓存
3、 composer update 更新依赖

你按上面试一下看看有报错吗？

**Comment by xiucaiwu** [comment]
问题找到了是php.ini中disable_functions中禁用了proc_open缘故,注释掉就ok了
