### ISSUE TITLE
v4 版本中 no_check_route 该如何设置？

### ISSUE THREAD

**Issue by flywish** [phper666/jwt-auth#49]
在使用全局中间件的前提下，假如只有 `/user/login`  和 `/user/logout` 两个接口不做校验，config 配置中的 no_check_route， 应该怎么设置？
![image](https://user-images.githubusercontent.com/24400037/154249910-6df467e8-c39f-4a9f-9221-8bf6042a14c7.png)

如上图，其中只有设置了完整路径的有效，只有路由的路径无效，仍提示 “Missing token”。 
追踪代码发现，在进行 no_check_route 相关判断时，`jwt-auth/src/PathMatch.php`  的 `matchRoute()` 方法好像有问题

**Comment by phper666** [comment]
@flywish  路由不支持完整的url，只支持路径，你要把http://127.0.0.1:9501/user/login改为/user/login

**Comment by phper666** [comment]
jwt.php配置里面也有注释，具体你可以看看注释

**Comment by phper666** [comment]
@flywish 你使用了哪个中间件呢？具体你可以看看Phper666\JWTAuth\Middleware\JWTAuthDefaultSceneMiddleware的逻辑，理应当前路由被匹配到后，会直接handle下个中间件了，不会进行任何jwt token校验的处理了

**Comment by phper666** [comment]
如何使用这个no_check_route,实际配置文件里面有注释，具体可以看看注释

**Comment by phper666** [comment]
no_check_route的路径也支持正则的方式

**Comment by flywish** [comment]
就是使用 /user/login无效



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月16日(周三) 晚上7:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [phper666/jwt-auth] v4 版本中 no_check_route 该如何设置？ (Issue #49)




 
no_check_route的路径也支持正则的方式
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by phper666** [comment]
有什么报错吗？能否上传下你的demo我拉取测试下？

**Comment by phper666** [comment]
我大概知道了，user/logout不能跳过token的校验，jwt的logout是必须要token才行，因为会把这个token加入到黑名单中

**Comment by flywish** [comment]
### 环境 
- hyperf：v2.2 
- jwt-auth：v4.0
### 具体代码

1. 配置全局no_check_route， 在 `config/autoland/jwt.php` 中设置 `'no_check_route' => [
        ["**", "/user/login"],
    ],`
![image](https://user-images.githubusercontent.com/24400037/154394268-7f5dc996-80bb-41cc-a9a3-f5d04e0bc9f7.png)
2. 使用全局中间件，使用 `JWTAuthDefaultSceneMiddleware`, 在 `config/autoload/middlewares.php` 中 设置 `'http' => [
        Hyperf\Validation\Middleware\ValidationMiddleware::class,
        Phper666\JWTAuth\Middleware\JWTAuthDefaultSceneMiddleware::class
    ]`
![image](https://user-images.githubusercontent.com/24400037/154394517-ae1668f1-32dd-4fbd-995d-f5491d1a1126.png)
3. 添加 `/user/login` 路由，添加对应控制器和方法
![image](https://user-images.githubusercontent.com/24400037/154394679-42722534-a1ee-4251-976c-d22ff6fc6c12.png)
4. 请求接口， 发现 no_check-route 中的设置并未生效，`/user/login` 接口仍是400 ，提示 "Missing token"
![image](https://user-images.githubusercontent.com/24400037/154395372-bfbb167b-8d7e-4324-b996-3a89b00f4f32.png)

**Comment by phper666** [comment]
@flywish 中间件的问题，更新到v4.0.3可以解决这个问题，或者使用其它提供的中间件

**Comment by flywish** [comment]
OK， 看到你的解决方案了，和我预想的差不多。
