### ISSUE TITLE
matchRoute在scene下，获取no_check_route错误

### ISSUE THREAD

**Issue by ShrRung** [phper666/jwt-auth#50]
![image](https://user-images.githubusercontent.com/13992298/161384894-a262e060-0801-473d-9606-86d9826641a3.png)

![image](https://user-images.githubusercontent.com/13992298/161384885-eae9a9cb-c99a-4ede-ab7a-8dbbc41cac2f.png)

如上图红框处，获取配置scene时少了一级

**Comment by ShrRung** [comment]
v4.0.3 版本号

**Comment by phper666** [comment]
有报错信息吗？不是少了一级，这个jwtConfig是经过过滤的，具体你找找里面的逻辑

**Comment by ShrRung** [comment]
![image](https://user-images.githubusercontent.com/13992298/162007015-087a0118-f522-49bf-8514-87ee4cbd0bd1.png)
没报错的，抱歉，是我描述得不对，只是matchRoute方法里的 noCheckRoute都是取的配置文件里的公共的no_check_route，不同scene的no_check_route是没法区分就了

**Comment by phper666** [comment]
@hedeqiang 你看下jwt的初始化那里，有对不同scene场景的配置进行合并

**Comment by phper666** [comment]
先关闭了，有问题再重新打开
