### ISSUE TITLE
单点登录 为什么不好使？ 

### ISSUE THREAD

**Issue by tieshengdetie** [phper666/jwt-auth#51]
login_type 设置的事sso 两个客户端同时登录，token没有失效，都可以用

**Comment by tieshengdetie** [comment]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/23207416/161435426-9a1a0d82-eff0-41e8-b39a-f68a1c89b9ac.png">
验证token时没有对sso进行处理？

**Comment by phper666** [comment]
使用单点登录必须要使用缓存，你是分布式部署？还是单机部署?

**Comment by phper666** [comment]
@tieshengdetie 在你的登录逻辑里面加入刷新token的操作，正常的逻辑是登录->生成token->刷新token->返回刷新的token，此时所有的客户端token都会失效，只有刷新token的那个会生效
