### ISSUE TITLE
获取token报错

### ISSUE THREAD

**Issue by cxjhk** [phper666/jwt-auth#52]
PHP Fatal error:  Cannot redeclare generateMysqlConfig()

**Comment by phper666** [comment]
这个明显不是jwt-auth这个包报出来的，你查查具体的错误



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月12日(周二) 下午5:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [phper666/jwt-auth] 获取token报错 (Issue #52)




 
PHP Fatal error:  Cannot redeclare generateMysqlConfig()

**Comment by cxjhk** [comment]
没事 我自己关了
