### ISSUE TITLE
4.0.5 token 一直失效

### ISSUE THREAD

**Issue by xshiyun** [phper666/jwt-auth#54]
4.0.5 token 一直失效

**Comment by phper666** [comment]
@xshiyun 单点登录还是多点登录？可以上传配置看下吗？

**Comment by xshiyun** [comment]
单点登录
JWT.php 275行  `return $iatTime <= $cacheValue['valid_until'];`  
是否应该是 `return $iatTime < $cacheValue['valid_until']`

**Comment by xshiyun** [comment]
好了，以前版本单点登录不自动加没名单，我自己手动加的，现在逻辑变了，导致出的问题！
还有个需求，Payload 里能不能加上 sub

**Comment by phper666** [comment]
不是逻辑变了，是我重构4.0的时候没有遗漏了这个功能，payload本身就支持自定义的，你可以这样：
```
// 自定义数据到Payload
$userData = [
                'ab' => '1123',
                'uid' => 1, // 如果使用单点登录，必须存在配置文件中的sso_key的值，一般设置为用户的id
                'username' => 'xx',
            ];
// 使用默认场景登录
$token = $this->jwt->getToken('default', $userData);
```

**Comment by phper666** [comment]
新增jwt可以自定义payload的sub、iss、aud字段，可以更新到v4.0.6

**Comment by xshiyun** [comment]
thanks
