### ISSUE TITLE
偶发出现该问题

### ISSUE THREAD

**Issue by dreamyi12** [phper666/jwt-auth#56]
Lcobucci\JWT\Validation\Constraint\IssuedBy::__construct(): Argument #1 must be of type string, null given, called in /project-lib/phper666/jwt-auth/src/JWT.php on line 551[15] in /www/vendor/lcobucci/jwt/src/Va
lidation/Constraint/IssuedBy.php

**Comment by phper666** [comment]
issueBy你传了null进去吗？这个只支持字符串类型.或者你用的不是jwt-auth生成的token，jwt-auth做了issueBy的校验 @dreamyi12

**Comment by phper666** [comment]
未见有回复，先直接关闭掉该isset
