### ISSUE TITLE
Object of class Lcobucci\JWT\Token\Plain could not be converted to string[647] 

### ISSUE THREAD

**Issue by starry16** [phper666/jwt-auth#57]
升级到4.0.7版本报这个错误

**Comment by phper666** [comment]
调用了哪个方法出错的，这个看起来对象不能转成字符串



---Original---
From: ***@***.***&gt;
Date: Tue, May 24, 2022 16:48 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [phper666/jwt-auth] Object of class Lcobucci\JWT\Token\Plain couldnot be converted to string[647]  (Issue #57)




 
升级到4.0.7版本报这个错误

**Comment by phper666** [comment]
未见有回复，先直接关闭掉该isset
