### ISSUE TITLE
JWTCommand.$name属性类型问题

### ISSUE THREAD

**Issue by tengfei31** [phper666/jwt-auth#58]
```
namespace Phper666\JWTAuth\Command;

use Hyperf\Command\Command as HyperfCommand;

class JWTCommand extends HyperfCommand
{
    /**
     * 执行的命令行
     *
     * @var string
     */
    protected $name = 'jwt:publish';
}
```
这里的name应该改为```protected ?string $name = 'jwt:publish';```
因为他的父级属性限制了，不然的话执行```php bin/hyperf.php vendor:publish phper666/jwt-auth```会报一个致命错误
```
PHP Fatal error:  Type of Phper666\JWTAuth\Command\JWTCommand::$name must be ?string (as in class Hyperf\Command\Command) in /www/php/workstation/vendor/phper666/jwt-auth/src/Command/JWTCommand.php on line 55
```

使用版本：phper666/jwt-auth:~4.0.0
本机环境：php8.0.14

**Comment by chongeric** [comment]
目前我的hyperf3.0就是出现了这个问题，版本跟环境与楼主一致，
![image](https://user-images.githubusercontent.com/30619185/211713258-b3690e88-72e0-4a3f-8afb-2d42b7f8c281.png)
