### ISSUE TITLE
token 续签

### ISSUE THREAD

**Issue by YanCunJu** [phper666/jwt-auth#62]
是否考虑增加 token 续签功能，在 token 快要过期时自动续签，换一个新的 token 给客户端

**Comment by phper666** [comment]
这个需要你业务方去实现呀，这个包有提供刷新token。你可以在客户端使用的token还剩10分钟内的时候就去刷新token，然后重新颁发token给客户端，让客户端处理续签

**Comment by YanCunJu** [comment]
```
"exp": {
		"date": "2023-03-30 11:43:06.000000",
		"timezone_type": 1,
		"timezone": "+00:00"
	}
```
这里的 timezone 是表示零时区吗，需要先取出 exp下面的 date，然后加 8 小时和现在时间对比，如果是还剩 10 分钟，刷新 token ?

**Comment by YanCunJu** [comment]
我
