### ISSUE TITLE
4.0.8 JWTCommand::$name must not be defined 

### ISSUE THREAD

**Issue by xshiyun** [phper666/jwt-auth#63]
PHP Fatal error:  Type of Phper666\JWTAuth\Command\JWTCommand::$name must not be defined (as in class Hyperf\Command\Command) in /www/wwwroot/senseu-v2/vendor/phper666/jwt-auth/src/Command/JWTCommand.php on line 55

**Comment by phper666** [comment]
发下你的php版本号、hyperf版本号，我测试一下，在php7.4以上版本测试没有出现过这个问题

**Comment by xshiyun** [comment]
hyperf 2.2

**Comment by xshiyun** [comment]
hyperf/command 3.0 这个库改了

**Comment by phper666** [comment]
emmm...晚上我测试一下看看

**Comment by phper666** [comment]
更新到v4.0.9问题就会解决，具体可以看看这个pr：https://github.com/phper666/jwt-auth/pull/64/commits/32b62e2c1427f72e92a6149006a88bf7edbda3b8
