### ISSUE TITLE
多场景的使用问题

### ISSUE THREAD

**Issue by YanCunJu** [phper666/jwt-auth#66]
假如有两个场景，一个用 default，一个场景用 application，两个场景生成 token 都没有问题，`middlewaress.php` 中怎么配置呢？添加：
 ```
 \Phper666\JWTAuth\Middleware\JWTAuthDefaultSceneMiddleware::class,
\Phper666\JWTAuth\Middleware\JWTAuthApplicationSceneMiddleware::class,
```
两个都添加，中间件会都执行 process，总会有一个场景不对，然后抛出 `TokenValidException`

**Comment by phper666** [comment]
没太懂你的意思，你意思是用两个场景的token都能访问你的接口吗？

**Comment by YanCunJu** [comment]
是的，一个应用，两种不同身份的用户，需要两个场景的token



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月26日(周三) 晚上8:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [phper666/jwt-auth] 多场景的使用问题 (Issue #66)




 
没太懂你的意思，你意思是用两个场景的token都能访问你的接口吗？

**Comment by phper666** [comment]
你可以看看\Phper666\JWTAuth\Middleware\JWTAuthApplicationSceneMiddleware::class的实现，这个你可以按照这个中间件实现一个自己要验证场景的中间件出来

**Comment by phper666** [comment]
@YanCunJu 解决了吗？如果解决了我先关闭了

**Comment by YanCunJu** [comment]
OK, 解决了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月29日(周六) 上午10:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [phper666/jwt-auth] 多场景的使用问题 (Issue #66)




 
@YanCunJu 解决了吗？如果解决了我先关闭了
