### ISSUE TITLE
使用application场景

### ISSUE THREAD

**Issue by cxjhk** [phper666/jwt-auth#67]
使用application场景，valid_until和iattime时间一致，导致token刚签发出来就失效了，进入黑名单验证去了

![image](https://github.com/phper666/jwt-auth/assets/23472375/53742d4a-ffe3-4fc4-9ce0-aacb6f46cf20)

而且是偶发的

**Comment by cxjhk** [comment]
<img width="762" alt="image" src="https://github.com/phper666/jwt-auth/assets/23472375/047f6842-2a47-4a84-aadb-1e5cddebb38f">

**Comment by phper666** [comment]
你这个是在单点登录的类型下吗？ @cxjhk

**Comment by phper666** [comment]
没理由呀，单点登录模式下，valid_unitl为当前新token签发时间-1秒，所以理论上，不会出现刚签发就失效的问题呀，因为新签发的token永远会比valid_unitl多一秒，除非是多请求了一次，上一次的token就会失效

**Comment by phper666** [comment]
你这边大概是什么场景下出现这个问题的呢？可以大概描述一下吗？

**Comment by phper666** [comment]
@cxjhk 你更新到v4.0.10问题应该就解决了
