### ISSUE TITLE
异常处理

### ISSUE THREAD

**Issue by hedeqiang** [phper666/jwt-auth#7]
现在 token 不传，或者失效，客户端会直接返回 500 ，并在控制器 返回 `Token authentication does not pass[124]` 

有没有直接处理的方法，直接返回报错信息

**Comment by phper666** [comment]
token不传会报500，并且返回A token is required，token失效会返回401，并且返回信息为Token authentication does not pass，你可以看看jwt.php这个类，里面有详情，我只会抛两种异常类型信息，你可以看看exception这个目录。

**Comment by phper666** [comment]
@hedeqiang 你可以统一处理，在你项目统一异常那里判断抛出的异常是否为TokenValidException和JWTException类型，然后你自己再做处理返回

**Comment by hedeqiang** [comment]
@phper666  难道是我姿势不对吗？ 不传 Token 返回也是 500，Token 失效 还是 500

正常情况：
![image](https://user-images.githubusercontent.com/31909061/66697875-0d4c3780-ed0c-11e9-9e54-21ecabda7824.png)

Token 失效：
![image](https://user-images.githubusercontent.com/31909061/66697893-248b2500-ed0c-11e9-8310-979aa58c4300.png)

不传递 Token：
![image](https://user-images.githubusercontent.com/31909061/66697906-379df500-ed0c-11e9-95c5-a099e26a1e0d.png)

**Comment by hedeqiang** [comment]
我处理了下 异常 ，不传 token 回如下：
![image](https://user-images.githubusercontent.com/31909061/66698175-3bcb1200-ed0e-11e9-9d3f-3d31fb1e4044.png)

**Comment by hedeqiang** [comment]
其实无所谓，不传也是 401 ，没问题
