### ISSUE TITLE
jwt 配置无法读取apollo配置

### ISSUE THREAD

**Issue by hym12121** [phper666/jwt-auth#72]
hyperf 版本：2.2
jwt-auth:4.0.x
php:8.0
分析原因：
 jwt类在初始化是使用make方法注入ConfigInterface接口，make实例化的config读取的是项目文件的配置项，apollo配置是在项目初始化时写入系统变量中，无法被make实例化的config读取到，
![image](https://github.com/phper666/jwt-auth/assets/160588480/c94a6b5f-37ef-4346-aa2e-b8542d9a6fc4)

![image](https://github.com/phper666/jwt-auth/assets/160588480/6650c002-ee25-4287-beee-4544c7c6b9f5)

是否可以这样处理：
在phper666\jwt-auth\src\Functions.php
增加：
![image](https://github.com/phper666/jwt-auth/assets/160588480/5f8695b5-09bb-4e72-a08c-8d54f2bcf534)

将make改成build

![image](https://github.com/phper666/jwt-auth/assets/160588480/ff72cef9-a3fc-4604-a2a4-dd3beb3127c9)

**Comment by phper666** [comment]
你们在使用apollo做配置中心的时候，不会把配置覆盖项目的config对象吗？如果不覆盖的话，你们项目是怎么获取到最新的配置中心配置的？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月20日(周二) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [phper666/jwt-auth] jwt 配置无法读取apollo配置 (Issue #72)




 
hyperf 版本：2.2
 jwt-auth:4.0.x
 php:8.0
 分析原因：
 jwt类在初始化是使用make方法注入ConfigInterface接口，make实例化的config读取的是项目文件的配置项，apollo配置是在项目初始化时写入系统变量中，无法被make实例化的config读取到，
 image.png (view on web)
 
image.png (view on web)
 
是否可以这样处理：
 在phper666\jwt-auth\src\Functions.php
 增加：
 image.png (view on web)
 
将make改成build
 
image.png (view on web)

**Comment by hym12121** [comment]
首先感谢作者百忙之中的回复：
我看了一下源码：
他读取apollo配置是放在了resolvedEntries数组中
vendor/hyperf/config-apollo/src/ApolloDriver.php类中的updateConfig方法中可以看到他引用了set方法
![image](https://github.com/phper666/jwt-auth/assets/160588480/ee4f4100-7b63-4736-8b7f-f415684bf104)

vendor/hyperf/di/src/Container.php类中set方法是将配置放入了resolvedEntries数组中，
![image](https://github.com/phper666/jwt-auth/assets/160588480/92f5cbb8-6164-4416-a9b5-3e9b9290a553)

vendor/hyperf/di/src/Container.php类中get方法是读取了这个数据，如果有是直接返回的
![image](https://github.com/phper666/jwt-auth/assets/160588480/7497ca22-41b4-48b0-b610-6bd527061105)
大佬可以测试一下

**Comment by phper666** [comment]
好的，还是没太懂，因为jwt就是从config实例里面去获取配置数据的，如果项目配置改为配置中心获取，应该也是能获取到才对。等晚点我使用配置中心测试试看看吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月20日(周二) 晚上7:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [phper666/jwt-auth] jwt 配置无法读取apollo配置 (Issue #72)




 
首先感谢作者百忙之中的回复：
 我看了一下源码：
 他读取apollo配置是放在了resolvedEntries数组中
 vendor/hyperf/config-apollo/src/ApolloDriver.php类中的updateConfig方法中可以看到他引用了set方法
 image.png (view on web)
 
vendor/hyperf/di/src/Container.php类中set方法是将配置放入了resolvedEntries数组中，
 image.png (view on web)
 
vendor/hyperf/di/src/Container.php类中get方法是读取了这个数据，如果有是直接返回的
 image.png (view on web)
 大佬可以测试一下

**Comment by phper666** [comment]
我测试了没有问题的，只不过你用官方的hyperf提供的apollo包的话，不支持解析apollo数组的配置，例如jwt.scene[0].application[0].secret="application"
这种配置，需要自己写一个配置解析。方案如下：
1、自行实现一个ApolloListener的配置监听类，自行实现配置加载到你项目的config对象实例里面
```
use Hyperf\ConfigCenter\Event\ConfigChanged;
use Hyperf\Database\Events\QueryExecuted;
use Hyperf\Event\Annotation\Listener;
use Hyperf\Event\Contract\ListenerInterface;
use Psr\Container\ContainerInterface;
use function Phper666\JWTAuth\make;

#[Listener]
class ApolloListener implements ListenerInterface
{

    public function __construct(ContainerInterface $container)
    {
    }

    public function listen(): array
    {
        return [
            ConfigChanged::class,
        ];
    }

    /**
     * @param QueryExecuted $event
     */
    public function process(object $event): void
    {
        if ($event instanceof ConfigChanged) {
            // TODO 自行实现配置加载
            $config = make(ConfigInterface::class);
            // TODO set jwt config
            // jwt config key eg: jwt.scene
            // 需要把jwt.scene[0]这种配置转为php支持的数组
            // 如果不知道这个jwt配置要按什么结构加载到config对象实例，你可以看下config目录下的jwt.php文件，里面就是一个jwt的配置数组，只不过里面的配置被加载到config对象的时候，会默认加上jwt前缀，可以通过$config->get("jwt.login_type")获取到对应的配置，可以去看一下hyperf配置的实现应该就懂了
            // $config->set('key', 'value');
        }
    }
}
```
2、下面这份是上面这个监听到的$event对象数据，自行实现上面TODO，把apollo获取到的配置解析加载到config对象实例里面：
```
object(Hyperf\ConfigCenter\Event\ConfigChanged)#910 (2) {
  ["current"]=>
  array(1) {
    ["application"]=>
    array(26) {
      ["jwt.no_check_route[0][0]"]=>
      string(4) ""**""
      ["jwt.no_check_route[0][1]"]=>
      string(12) ""/api/login""
      ["jwt.login_type"]=>
      string(6) ""mpop""
      ["jwt.sso_key"]=>
      string(5) ""uid""
      ["jwt.secret"]=>
      string(10) ""phper666""
      ["jwt.keys[0].public"]=>
      string(66) ""file:///app/www/hyperf-component/hyperf-skeleton/keys/public.key""
      ["jwt.keys[0].private"]=>
      string(67) ""file:///app/www/hyperf-component/hyperf-skeleton/keys/private.key""
      ["jwt.keys[0].passphrase"]=>
      string(5) ""111""
      ["jwt.ttl"]=>
      string(4) "7200"
      ["jwt.alg"]=>
      string(7) ""RS512""
      ["jwt.cache_prefix"]=>
      string(14) ""phper666:jwt""
      ["jwt.blacklist_enabled"]=>
      string(4) "true"
      ["jwt.blacklist_grace_period"]=>
      string(1) "0"
      ["jwt.issued_dy"]=>
      string(14) ""phper666/jwt""
      ["jwt.scene[0].default[0]"]=>
      string(2) """"
      ["jwt.scene[0].application[0].secret"]=>
      string(13) ""application""
      ["jwt.scene[0].application[0].login_type"]=>
      string(5) ""sso""
      ["jwt.scene[0].application[0].sso_key"]=>
      string(5) ""uid""
      ["jwt.scene[0].application[0].ttl"]=>
      string(4) "1800"
      ["jwt.scene[0].application1[0].secret"]=>
      string(14) ""application1""
      ["jwt.scene[0].application1[0].login_type"]=>
      string(5) ""sso""
      ["jwt.scene[0].application1[0].sso_key"]=>
      string(5) ""uid""
      ["jwt.scene[0].application1[0].ttl"]=>
      string(4) "3600"
      ["jwt.scene[0].application2[0].secret"]=>
      string(14) ""application2""
      ["jwt.scene[0].application2[0].login_type"]=>
      string(6) ""mpop""
      ["jwt.scene[0].application2[0].ttl"]=>
      string(4) "7200"
    }
  }
  ["previous"]=>
  array(0) {
  }
}

```
3、这份是apollo上的jwt配置，可以直接配置到你的apollo
```
jwt.no_check_route[0][0]="**"
jwt.no_check_route[0][1]="/api/login"
jwt.login_type="mpop"
jwt.sso_key="uid"
jwt.secret="phper666"
jwt.keys[0].public="file:///app/www/hyperf-component/hyperf-skeleton/keys/public.key"
jwt.keys[0].private="file:///app/www/hyperf-component/hyperf-skeleton/keys/private.key"
jwt.keys[0].passphrase="111"
jwt.ttl=7200
jwt.alg="RS512"
jwt.cache_prefix="phper666:jwt"
jwt.blacklist_enabled=true
jwt.blacklist_grace_period=0
jwt.issued_dy="phper666/jwt"
jwt.scene[0].default[0]=""
jwt.scene[0].application[0].secret="application"
jwt.scene[0].application[0].login_type="sso"
jwt.scene[0].application[0].sso_key="uid"
jwt.scene[0].application[0].ttl=1800

jwt.scene[0].application1[0].secret="application1"
jwt.scene[0].application1[0].login_type="sso"
jwt.scene[0].application1[0].sso_key="uid"
jwt.scene[0].application1[0].ttl=3600

jwt.scene[0].application2[0].secret="application2"
jwt.scene[0].application2[0].login_type="mpop"
jwt.scene[0].application2[0].ttl=7200
```

@hym12121

**Comment by phper666** [comment]
当然如果你自己有兴趣的话，也可以给官方提供这种这样的解析，实际在官方apollo的config更新逻辑里面加多一种配置解析就可以了

**Comment by phper666** [comment]
@hym12121 不知道上面的方案能解决你的问题吗？该issue我先关闭了，如果未能解决你再重新开启
