### ISSUE TITLE
PathMatch.php文件bug

### ISSUE THREAD

**Issue by quxiaojia** [phper666/jwt-auth#73]
第72行 foreach ($noCheckRouteData as $route) {}导致no_check_route失效应该去掉该循环
$noCheckMethod = $noCheckRouteData[0] ??null；$noCheckPath = $noCheckRouteData[1] ??null；

**Comment by phper666** [comment]
你传入的配置结构是什么？
@quxiaojia

**Comment by phper666** [comment]
没见有回复，我先关闭issues，如果问题还未解决，再重新打开
