### ISSUE TITLE
可以提交到官方组件库

### ISSUE THREAD

**Issue by tracenull** [phper666/jwt-auth#8]

**Comment by phper666** [comment]
会提交到官方那边去的，目前就是看看使用会不会有什么问题，没有问题就会提交过去

**Comment by hedeqiang** [comment]
我在使用😃

**Comment by hedeqiang** [comment]
把用户对象加入吧，我觉得还是很有必要的

**Comment by phper666** [comment]
好的，我有时间的时候就加入这个功能

**Comment by tracenull** [comment]
我模仿laravel jwt-auth加入了通过参数传token的方式

> 好的，我有时间的时候就加入这个功能

**Comment by phper666** [comment]
@tracenull jwt目前都是在请求头使用Authorization bearer的吧？如果要加入兼容token的验证，自己新写一个中间件，不使用jwt-auth这个包的中间件即可~
